### ISSUE TITLE
[multas] Integração STU

### ISSUE THREAD

**Issue by fernandascovino** [RJ-SMTR/maestro#153]
PR vinculado: #61 #157 

**TODO**

@fernandascovino 
- [x] Construir tabelas de finais de semana
- [x] Adicionar no BQ
- [ ] Alinhar com equipe BI como considerar fds (tipo_dia Feriado)

@Hellcassius 
- [ ] Mudar `detalhe_linha_onibus_completa` para considerar feriado
- [ ] Adicionar na `view` exclusão de feriados e fds
- [ ] Remover a condicional de feriado/fds na `sumario_multa_onibus_integrado_stu` (a `view` já vai retornar vazio)
